### ISSUE TITLE
TypeError: love.load() is not a function

### ISSUE THREAD

**Issue by desk467** [DaanHaaz/loveJS#4]
I tried to compile a small example, where was printed something on the screen, but the browser accused error: "love.load () is not a function". The error was on line in 1022 ..

**Comment by Sheepolution** [comment]
That's because it expects you to have at least a love.load function.

``` javascript
love.load = function () {

}

//Initialize love
love.run();
```

**Comment by desk467** [comment]
aahh '-'

i'm sorry ><
